name: "Cronjob Buy BTC"

on:
  schedule:
    - cron: "0 1,13 * * *"

jobs:
  buy-btc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install --force

      - name: Create Build Files
        run: npm run build

      - name: Buy BTC
        run: npm run wz-command daily-buy -- --asset=BTC --exchange=Bitget
        env:
          DATABASE_CA_PEM: ${{ secrets.DATABASE_CA_PEM }}
          DATABASE_CONNECT: ${{ secrets.DATABASE_CONNECT }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          X_BITGET_API_KEY: ${{ secrets.X_BITGET_API_KEY }}
          X_BITGET_API_SECRET: ${{ secrets.X_BITGET_API_SECRET }}
          X_BITGET_API_PASS: ${{ secrets.X_BITGET_API_PASS }}
